server:
  port: 8072

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
  security:
     oauth2:
       resourceserver:
         jwt:
           issuer-uri: http://localhost:8080/realms/master